In [210]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestRegressor

from collections import Counter
from sklearn.datasets import make_classification
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import pickle
import joblib

from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import pickle
import joblib

from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor


import seaborn as sns
from matplotlib import pyplot as plt

In [212]:
dtrain= pd.read_csv('./pm3_data/diamonds_train.csv')
dtrain

index_id        cut color  \
0      5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...    Premium     J   
1      6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...  Very Good     H   
2      d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...       Fair     G   
3      4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...       Good     D   
4      4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...      Ideal     G   
...                                                  ...        ...   ...   
40450  f0bc79169405ebeb24e308055156b946ffd819db9b4f75...      Ideal     G   
40451  339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...       Good     F   
40452  46957922b99954654c1deb8d854c3f069bf118b2ce9415...      Ideal     H   
40453  9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...      Ideal     J   
40454  a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...      Ideal     I   

      clarity  depth  carat  table     x     y     z  price       city  
0         VS2   62.4   1.21   58.0  6.83  6.79  4.25   4268      Dubai  
1         VS2   63.0   0.32   57.0  4.35  4.38  2.75    505   Kimberly  
2         VS1   65.5   0.71   55.0  5.62  5.53  3.65   2686  Las Vegas  
3         SI1   63.8   0.41   56.0  4.68  4.72  3.00    738   Kimberly  
4         SI1   60.5   1.02   59.0  6.55  6.51  3.95   4882      Dubai  
...       ...    ...    ...    ...   ...   ...   ...    ...        ...  
40450     VS1   62.7   1.34   57.0  7.10  7.04  4.43  10070    Antwerp  
40451     SI2   57.1   2.02   60.0  8.31  8.25  4.73  12615     Madrid  
40452     SI1   62.7   1.01   56.0  6.37  6.42  4.01   5457   Kimberly  
40453     VS1   61.9   0.33   54.3  4.45  4.47  2.76    456   Kimberly  
40454     SI1   62.0   1.24   58.0  6.83  6.88  4.25   6232     London  

[40455 rows x 12 columns]

In [213]:
dtrain.describe()

depth         carat         table             x             y  \
count  40455.000000  40455.000000  40455.000000  40455.000000  40455.000000   
mean      61.752841      0.797706     57.446133      5.729392      5.732819   
std        1.431725      0.475544      2.233535      1.124453      1.146650   
min       43.000000      0.200000     43.000000      0.000000      0.000000   
25%       61.000000      0.400000     56.000000      4.710000      4.720000   
50%       61.800000      0.700000     57.000000      5.690000      5.710000   
75%       62.500000      1.040000     59.000000      6.540000      6.540000   
max       79.000000      4.500000     95.000000     10.230000     58.900000   

                  z         price  
count  40455.000000  40455.000000  
mean       3.537154   3928.444469  
std        0.697062   3992.416147  
min        0.000000    326.000000  
25%        2.910000    945.000000  
50%        3.520000   2397.000000  
75%        4.035000   5331.000000  
max        8.060000  18823.000000

In [214]:
dtrain['carat'].median()

0.7

In [215]:
dtrain['price'].median()

2397.0

In [216]:
print(np.where(dtrain['carat'] > 0.80))

(array([    0,     4,     5, ..., 40451, 40452, 40454], dtype=int64),)


In [217]:
print(np.where(dtrain['x'] == 0))
print(np.where(dtrain['y'] == 0))
print(np.where(dtrain['z'] == 0))

(array([ 6465, 14815, 26192, 28029, 34423], dtype=int64),)
(array([ 6465, 26192, 28029, 34423], dtype=int64),)
(array([ 1606,  3945,  6465, 13839, 14815, 14891, 16425, 19856, 21602,
       24795, 26192, 26978, 28029, 34423, 34504, 34601], dtype=int64),)


In [218]:
dtrain.sort_values(by=['price'], inplace=True, ascending = False)
dtrain

index_id        cut color  \
7034   0929b60950cb33cc0a978ad4663611a54497bb4fe44b25...    Premium     I   
3990   ef501c2555ae9e3de6e23ae39393d64dac510d6d681ba6...  Very Good     G   
29107  8422ae9c93dc72b3ae57f40eb6a37ecca544506b9cf178...      Ideal     G   
25529  57be7e56de67f7ae840a06ca4dc42174c38cd24f8461fd...    Premium     I   
618    ee377871c73631fd6543ddb5164d0b48ea072daa207a91...    Premium     I   
...                                                  ...        ...   ...   
12084  5115faeecc0db1adcfda7bb7a3ffd0bbc008309e0e1dba...       Good     J   
20968  c2bd9d46d24d10ec4ec7d49f295c5555462df32247bb2b...    Premium     I   
18381  b3884138875a4fff84c082069e1f4adc178c3642c8b872...       Good     E   
9782   257e3cd0744845b83c0d1f8a114d5c04218844a0c8debe...      Ideal     E   
18377  a21cefec25404279928e2ffe9d49630f691600cd9d9a1e...    Premium     E   

      clarity  depth  carat  table     x     y     z  price           city  
7034      VS2   60.8   2.29   60.0  8.50  8.47  5.16  18823       Kimberly  
3990      SI1   63.5   2.00   56.0  7.90  7.97  5.04  18818         Madrid  
29107      IF   61.7   1.51   55.0  7.37  7.41  4.56  18806  New York City  
25529     SI1   61.8   2.29   59.0  8.52  8.45  5.24  18797          Surat  
618       VS1   60.8   2.00   59.0  8.13  8.02  4.91  18795       Kimberly  
...       ...    ...    ...    ...   ...   ...   ...    ...            ...  
12084     SI2   63.3   0.31   58.0  4.34  4.35  2.75    335       Tel Aviv  
20968     VS2   62.4   0.29   58.0  4.20  4.23  2.63    334       Kimberly  
18381     VS1   56.9   0.23   65.0  4.05  4.07  2.31    327         Zurich  
9782      SI2   61.5   0.23   55.0  3.95  3.98  2.43    326          Paris  
18377     SI1   59.8   0.21   61.0  3.89  3.84  2.31    326       Tel Aviv  

[40455 rows x 12 columns]

In [219]:
dtrain = dtrain.drop(['city'], axis =1)
dtrain

index_id        cut color  \
7034   0929b60950cb33cc0a978ad4663611a54497bb4fe44b25...    Premium     I   
3990   ef501c2555ae9e3de6e23ae39393d64dac510d6d681ba6...  Very Good     G   
29107  8422ae9c93dc72b3ae57f40eb6a37ecca544506b9cf178...      Ideal     G   
25529  57be7e56de67f7ae840a06ca4dc42174c38cd24f8461fd...    Premium     I   
618    ee377871c73631fd6543ddb5164d0b48ea072daa207a91...    Premium     I   
...                                                  ...        ...   ...   
12084  5115faeecc0db1adcfda7bb7a3ffd0bbc008309e0e1dba...       Good     J   
20968  c2bd9d46d24d10ec4ec7d49f295c5555462df32247bb2b...    Premium     I   
18381  b3884138875a4fff84c082069e1f4adc178c3642c8b872...       Good     E   
9782   257e3cd0744845b83c0d1f8a114d5c04218844a0c8debe...      Ideal     E   
18377  a21cefec25404279928e2ffe9d49630f691600cd9d9a1e...    Premium     E   

      clarity  depth  carat  table     x     y     z  price  
7034      VS2   60.8   2.29   60.0  8.50  8.47  5.16  18823  
3990      SI1   63.5   2.00   56.0  7.90  7.97  5.04  18818  
29107      IF   61.7   1.51   55.0  7.37  7.41  4.56  18806  
25529     SI1   61.8   2.29   59.0  8.52  8.45  5.24  18797  
618       VS1   60.8   2.00   59.0  8.13  8.02  4.91  18795  
...       ...    ...    ...    ...   ...   ...   ...    ...  
12084     SI2   63.3   0.31   58.0  4.34  4.35  2.75    335  
20968     VS2   62.4   0.29   58.0  4.20  4.23  2.63    334  
18381     VS1   56.9   0.23   65.0  4.05  4.07  2.31    327  
9782      SI2   61.5   0.23   55.0  3.95  3.98  2.43    326  
18377     SI1   59.8   0.21   61.0  3.89  3.84  2.31    326  

[40455 rows x 11 columns]

In [258]:
dtrain = dtrain.drop(dtrain.index[np.where(dtrain['carat'] > 0.9)])
dtrain = dtrain.drop(dtrain.index[np.where(dtrain['price'] < 500)])
dtrain = dtrain.drop(dtrain.index[np.where(dtrain['x'] == 0)])
dtrain = dtrain.drop(dtrain.index[np.where(dtrain['y'] == 0)])
dtrain = dtrain.drop(dtrain.index[np.where(dtrain['z'] == 0)])
dtrain = dtrain.drop(['index_id'], axis = 1)

dtrain

cut color clarity  depth  carat  table     x     y     z  price
6007   Very Good     D      IF   62.4   0.90   54.0  6.17  6.21  3.86   9182
33103      Ideal     D    VVS1   62.0   0.90   56.0  6.16  6.19  3.83   8979
5382   Very Good     D      IF   59.7   0.83   53.0  6.14  6.23  3.69   7889
25650  Very Good     E      IF   63.9   0.90   55.0  6.05  6.09  3.88   7747
2846     Premium     D    VVS1   61.3   0.90   59.0  6.18  6.12  3.77   7711
...          ...   ...     ...    ...    ...    ...   ...   ...   ...    ...
6902   Very Good     F     SI1   62.1   0.30   60.0  4.26  4.28  2.65    500
26214    Premium     H    VVS2   59.2   0.23   61.0  4.04  4.00  2.38    500
17605  Very Good     F     SI1   61.7   0.30   59.0  4.29  4.33  2.66    500
31931  Very Good     I     SI2   62.7   0.38   58.0  4.57  4.61  2.88    500
11832  Very Good     F     SI1   62.1   0.30   61.0  4.25  4.29  2.65    500

[23903 rows x 10 columns]

In [259]:
cat_features = ['cut','color','clarity']
dtrain_one_hot_encoding = pd.get_dummies(dtrain[cat_features], 
                                          columns=['cut','color','clarity'], 
                                          drop_first=True)
dtrain_one_hot_encoding

target = dtrain['price']

In [260]:
dtrain_one_hot_encoding.columns

Index(['cut_Good', 'cut_Ideal', 'cut_Premium', 'cut_Very Good', 'color_E',
       'color_F', 'color_G', 'color_H', 'color_I', 'color_J', 'clarity_IF',
       'clarity_SI1', 'clarity_SI2', 'clarity_VS1', 'clarity_VS2',
       'clarity_VVS1', 'clarity_VVS2'],
      dtype='object')

In [274]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(dtrain_one_hot_encoding)
scaled_data
dtrain_one_hot_encoding

cut_Good  cut_Ideal  cut_Premium  cut_Very Good  color_E  color_F  \
6007          0          0            0              1        0        0   
33103         0          1            0              0        0        0   
5382          0          0            0              1        0        0   
25650         0          0            0              1        1        0   
2846          0          0            1              0        0        0   
...         ...        ...          ...            ...      ...      ...   
6902          0          0            0              1        0        1   
26214         0          0            1              0        0        0   
17605         0          0            0              1        0        1   
31931         0          0            0              1        0        0   
11832         0          0            0              1        0        1   

       color_G  color_H  color_I  color_J  clarity_IF  clarity_SI1  \
6007         0        0        0        0           1            0   
33103        0        0        0        0           0            0   
5382         0        0        0        0           1            0   
25650        0        0        0        0           1            0   
2846         0        0        0        0           0            0   
...        ...      ...      ...      ...         ...          ...   
6902         0        0        0        0           0            1   
26214        0        1        0        0           0            0   
17605        0        0        0        0           0            1   
31931        0        0        1        0           0            0   
11832        0        0        0        0           0            1   

       clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
6007             0            0            0             0             0  
33103            0            0            0             1             0  
5382             0            0            0             0             0  
25650            0            0            0             0             0  
2846             0            0            0             1             0  
...            ...          ...          ...           ...           ...  
6902             0            0            0             0             0  
26214            0            0            0             0             1  
17605            0            0            0             0             0  
31931            1            0            0             0             0  
11832            0            0            0             0             0  

[23903 rows x 17 columns]

In [269]:
target

6007     9182
33103    8979
5382     7889
25650    7747
2846     7711
         ... 
6902      500
26214     500
17605     500
31931     500
11832     500
Name: price, Length: 23903, dtype: int64

In [270]:
X_train, X_validation, y_train, y_validation = train_test_split(scaled_data, target, random_state = 42, test_size = 0.2)

In [271]:
# Se entrena el modelo:

model = RandomForestRegressor()
model.fit(X = X_train, y = y_train)

RandomForestRegressor()

In [272]:
# Métrica de error:

# Primero se hace predicción del 20%:
y_pred = model.predict(X_validation)

mean_squared_error(y_validation, y_pred, squared=False)

989.2048705086676

In [245]:
diamond_test= pd.read_csv('./pm3_data/diamonds_test.csv')
diamond_test

id  carat        cut color clarity  depth  table     x     y     z  \
0          0   0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67   
1          1   1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18   
2          2   1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57   
3          3   0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90   
4          4   0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19   
...      ...    ...        ...   ...     ...    ...    ...   ...   ...   ...   
13480  13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30   
13481  13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56   
13482  13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53   
13483  13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45   
13484  13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94   

                city  
0          Amsterdam  
1              Surat  
2           Kimberly  
3           Kimberly  
4          Amsterdam  
...              ...  
13480      Amsterdam  
13481  New York City  
13482       Tel Aviv  
13483          Surat  
13484  New York City  

[13485 rows x 11 columns]

In [246]:
# Predicción:

diamond_test= pd.read_csv('./pm3_data/diamonds_test.csv')
diamond_test= diamond_test.drop(['city'], axis =1)

cat_features = ['cut', 'color', 'clarity']
dtest_one_hot_encoding = pd.get_dummies(diamond_test[cat_features], 
                                          columns=['cut', 'color', 'clarity'], 
                                          drop_first=True)

scaler = StandardScaler()
scaled_data_test = scaler.fit_transform(dtest_one_hot_encoding)
scaled_data_test


y_pred = model.predict(scaled_data_test)

In [231]:
diamond_test.shape

(13485, 10)

In [247]:
# Submission

submission = pd.DataFrame({'id': diamond_test['id'], 'price': y_pred})

In [248]:
submission.head()

id        price
0   0  1895.963931
1   1  1301.874368
2   2  1428.142032
3   3  1895.963931
4   4  1903.364269

In [249]:
submission.to_csv ('./pm3_data/submission3.csv', index=False)